Pastikan Direktori dan Nama File Benar

diff --git a/.github/workflows/apk_only.yml b/.github/workflows/apk_only.yml
--- a/.github/workflows/apk_only.yml
+++ b/.github/workflows/apk_only.yml
@@ -129,7 +129,12 @@ jobs:
         env:
           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
         run: |
-          APK_PATH=$(find ${{ steps.vars.outputs.dir }} -name "app-release.apk" | head -n 1)
+          APK_PATH=$(find ${{ steps.vars.outputs.dir }} -name "app-release.apk")
+        echo "Looking for APK at: $APK_PATH"
+          if [ ! -f "$APK_PATH" ]; then
+            echo "Error APK file not found!"
+            exit 1
+          fi
           npx firebase-tools appdistribution:distribute "$APK_PATH" \
             --app "${{ steps.vars.outputs.app_id }}" \
             --groups "sphere" \
